apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lutri2-mongodb-pvc
  labels:
    stack: lutri2
    component: lutri2-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi